// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package contracts

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7b8cbe4DecodePrototodoPkgDomainContracts(in *jlexer.Lexer, out *UserContext) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userType":
			out.UserType = string(in.String())
		case "id":
			out.Id = string(in.String())
		case "role":
			if in.IsNull() {
				in.Skip()
				out.Role = nil
			} else {
				in.Delim('[')
				if out.Role == nil {
					if !in.IsDelim(']') {
						out.Role = make([]string, 0, 4)
					} else {
						out.Role = []string{}
					}
				} else {
					out.Role = (out.Role)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Role = append(out.Role, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "features":
			if in.IsNull() {
				in.Skip()
				out.Features = nil
			} else {
				in.Delim('[')
				if out.Features == nil {
					if !in.IsDelim(']') {
						out.Features = make([]string, 0, 4)
					} else {
						out.Features = []string{}
					}
				} else {
					out.Features = (out.Features)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.Features = append(out.Features, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts(out *jwriter.Writer, in UserContext) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserType != "" {
		const prefix string = ",\"userType\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.UserType))
	}
	if in.Id != "" {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Id))
	}
	if len(in.Role) != 0 {
		const prefix string = ",\"role\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v3, v4 := range in.Role {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	if len(in.Features) != 0 {
		const prefix string = ",\"features\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Features {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserContext) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserContext) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserContext) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserContext) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts1(in *jlexer.Lexer, out *UpdateTaskCommand) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "id":
			out.Id = string(in.String())
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				*out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "SagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts1(out *jwriter.Writer, in UpdateTaskCommand) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.Id != "" {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Id))
	}
	if in.Title != nil {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Title))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Description))
	}
	if in.SagaId != nil {
		const prefix string = ",\"SagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateTaskCommand) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateTaskCommand) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateTaskCommand) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateTaskCommand) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts1(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts2(in *jlexer.Lexer, out *TaskEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = uint64(in.Uint64())
		case "sagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		case "stream":
			out.Stream = string(in.String())
		case "streamId":
			out.StreamId = string(in.String())
		case "version":
			out.Version = uint64(in.Uint64())
		case "event":
			out.Event = string(in.String())
		case "eventTime":
			if in.IsNull() {
				in.Skip()
				out.EventTime = nil
			} else {
				if out.EventTime == nil {
					out.EventTime = new(timestamppb.Timestamp)
				}
				easyjson7b8cbe4DecodeGoogleGolangOrgProtobufTypesKnownTimestamppb(in, out.EventTime)
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				if out.Data == nil {
					out.Data = new(TaskData)
				}
				(*out.Data).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts2(out *jwriter.Writer, in TaskEvent) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Id))
	}
	if in.SagaId != nil {
		const prefix string = ",\"sagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	if in.Stream != "" {
		const prefix string = ",\"stream\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Stream))
	}
	if in.StreamId != "" {
		const prefix string = ",\"streamId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StreamId))
	}
	if in.Version != 0 {
		const prefix string = ",\"version\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.Version))
	}
	if in.Event != "" {
		const prefix string = ",\"event\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Event))
	}
	if in.EventTime != nil {
		const prefix string = ",\"eventTime\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson7b8cbe4EncodeGoogleGolangOrgProtobufTypesKnownTimestamppb(out, *in.EventTime)
	}
	if in.Data != nil {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Data).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TaskEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TaskEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TaskEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TaskEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts2(l, v)
}
func easyjson7b8cbe4DecodeGoogleGolangOrgProtobufTypesKnownTimestamppb(in *jlexer.Lexer, out *timestamppb.Timestamp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "seconds":
			out.Seconds = int64(in.Int64())
		case "nanos":
			out.Nanos = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodeGoogleGolangOrgProtobufTypesKnownTimestamppb(out *jwriter.Writer, in timestamppb.Timestamp) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Seconds != 0 {
		const prefix string = ",\"seconds\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.Seconds))
	}
	if in.Nanos != 0 {
		const prefix string = ",\"nanos\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Nanos))
	}
	out.RawByte('}')
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts3(in *jlexer.Lexer, out *TaskEntityList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tasks":
			if in.IsNull() {
				in.Skip()
				out.Tasks = nil
			} else {
				in.Delim('[')
				if out.Tasks == nil {
					if !in.IsDelim(']') {
						out.Tasks = make([]*TaskEntity, 0, 8)
					} else {
						out.Tasks = []*TaskEntity{}
					}
				} else {
					out.Tasks = (out.Tasks)[:0]
				}
				for !in.IsDelim(']') {
					var v7 *TaskEntity
					if in.IsNull() {
						in.Skip()
						v7 = nil
					} else {
						if v7 == nil {
							v7 = new(TaskEntity)
						}
						(*v7).UnmarshalEasyJSON(in)
					}
					out.Tasks = append(out.Tasks, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts3(out *jwriter.Writer, in TaskEntityList) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Tasks) != 0 {
		const prefix string = ",\"tasks\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v8, v9 := range in.Tasks {
				if v8 > 0 {
					out.RawByte(',')
				}
				if v9 == nil {
					out.RawString("null")
				} else {
					(*v9).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TaskEntityList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TaskEntityList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TaskEntityList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TaskEntityList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts3(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts4(in *jlexer.Lexer, out *TaskEntity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "version":
			out.Version = uint64(in.Uint64())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "status":
			out.Status = Status(in.Int32())
		case "createdDateTime":
			if in.IsNull() {
				in.Skip()
				out.CreatedDateTime = nil
			} else {
				if out.CreatedDateTime == nil {
					out.CreatedDateTime = new(timestamppb.Timestamp)
				}
				easyjson7b8cbe4DecodeGoogleGolangOrgProtobufTypesKnownTimestamppb(in, out.CreatedDateTime)
			}
		case "updatedDateTime":
			if in.IsNull() {
				in.Skip()
				out.UpdatedDateTime = nil
			} else {
				if out.UpdatedDateTime == nil {
					out.UpdatedDateTime = new(timestamppb.Timestamp)
				}
				easyjson7b8cbe4DecodeGoogleGolangOrgProtobufTypesKnownTimestamppb(in, out.UpdatedDateTime)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts4(out *jwriter.Writer, in TaskEntity) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	if in.Version != 0 {
		const prefix string = ",\"version\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.Version))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.Status != 0 {
		const prefix string = ",\"status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Status))
	}
	if in.CreatedDateTime != nil {
		const prefix string = ",\"createdDateTime\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson7b8cbe4EncodeGoogleGolangOrgProtobufTypesKnownTimestamppb(out, *in.CreatedDateTime)
	}
	if in.UpdatedDateTime != nil {
		const prefix string = ",\"updatedDateTime\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson7b8cbe4EncodeGoogleGolangOrgProtobufTypesKnownTimestamppb(out, *in.UpdatedDateTime)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TaskEntity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TaskEntity) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TaskEntity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TaskEntity) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts4(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts5(in *jlexer.Lexer, out *TaskData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				*out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(Status)
				}
				*out.Status = Status(in.Int32())
			}
		case "randomMap":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.RandomMap = make(map[string]string)
				} else {
					out.RandomMap = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v10 string
					v10 = string(in.String())
					(out.RandomMap)[key] = v10
					in.WantComma()
				}
				in.Delim('}')
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
				out.Metadata = nil
			} else {
				if out.Metadata == nil {
					out.Metadata = new(structpb.Struct)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Metadata).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts5(out *jwriter.Writer, in TaskData) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Title != nil {
		const prefix string = ",\"title\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Title))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Description))
	}
	if in.Status != nil {
		const prefix string = ",\"status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(*in.Status))
	}
	if len(in.RandomMap) != 0 {
		const prefix string = ",\"randomMap\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v11First := true
			for v11Name, v11Value := range in.RandomMap {
				if v11First {
					v11First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v11Name))
				out.RawByte(':')
				out.String(string(v11Value))
			}
			out.RawByte('}')
		}
	}
	if in.Metadata != nil {
		const prefix string = ",\"metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.Metadata).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TaskData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TaskData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TaskData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TaskData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts5(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts6(in *jlexer.Lexer, out *QuoteData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "quote":
			if in.IsNull() {
				in.Skip()
				out.Quote = nil
			} else {
				if out.Quote == nil {
					out.Quote = new(string)
				}
				*out.Quote = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts6(out *jwriter.Writer, in QuoteData) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Quote != nil {
		const prefix string = ",\"quote\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Quote))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v QuoteData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v QuoteData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *QuoteData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *QuoteData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts6(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts7(in *jlexer.Lexer, out *ProgressTaskCommand) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "id":
			out.Id = string(in.String())
		case "SagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts7(out *jwriter.Writer, in ProgressTaskCommand) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.Id != "" {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Id))
	}
	if in.SagaId != nil {
		const prefix string = ",\"SagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProgressTaskCommand) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProgressTaskCommand) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProgressTaskCommand) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProgressTaskCommand) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts7(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts8(in *jlexer.Lexer, out *ListTasksQuery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "pageNumber":
			out.PageNumber = uint32(in.Uint32())
		case "countPerPage":
			out.CountPerPage = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts8(out *jwriter.Writer, in ListTasksQuery) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.PageNumber != 0 {
		const prefix string = ",\"pageNumber\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint32(uint32(in.PageNumber))
	}
	if in.CountPerPage != 0 {
		const prefix string = ",\"countPerPage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint32(uint32(in.CountPerPage))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListTasksQuery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListTasksQuery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListTasksQuery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListTasksQuery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts8(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts9(in *jlexer.Lexer, out *GetQuoteQuery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts9(out *jwriter.Writer, in GetQuoteQuery) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetQuoteQuery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetQuoteQuery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetQuoteQuery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetQuoteQuery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts9(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts10(in *jlexer.Lexer, out *DeleteTaskCommand) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "id":
			out.Id = string(in.String())
		case "SagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts10(out *jwriter.Writer, in DeleteTaskCommand) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.Id != "" {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Id))
	}
	if in.SagaId != nil {
		const prefix string = ",\"SagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteTaskCommand) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteTaskCommand) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteTaskCommand) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteTaskCommand) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts10(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts11(in *jlexer.Lexer, out *CreateTaskCommand) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "SagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts11(out *jwriter.Writer, in CreateTaskCommand) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.SagaId != nil {
		const prefix string = ",\"SagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTaskCommand) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTaskCommand) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTaskCommand) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTaskCommand) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts11(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts12(in *jlexer.Lexer, out *CreateQuoteCommand) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "quote":
			out.Quote = string(in.String())
		case "SagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts12(out *jwriter.Writer, in CreateQuoteCommand) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.Quote != "" {
		const prefix string = ",\"quote\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Quote))
	}
	if in.SagaId != nil {
		const prefix string = ",\"SagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateQuoteCommand) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateQuoteCommand) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateQuoteCommand) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateQuoteCommand) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts12(l, v)
}
func easyjson7b8cbe4DecodePrototodoPkgDomainContracts13(in *jlexer.Lexer, out *CompleteTaskCommand) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userContext":
			if in.IsNull() {
				in.Skip()
				out.UserContext = nil
			} else {
				if out.UserContext == nil {
					out.UserContext = new(UserContext)
				}
				(*out.UserContext).UnmarshalEasyJSON(in)
			}
		case "id":
			out.Id = string(in.String())
		case "SagaId":
			if in.IsNull() {
				in.Skip()
				out.SagaId = nil
			} else {
				if out.SagaId == nil {
					out.SagaId = new(string)
				}
				*out.SagaId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b8cbe4EncodePrototodoPkgDomainContracts13(out *jwriter.Writer, in CompleteTaskCommand) {
	out.RawByte('{')
	first := true
	_ = first
	if in.UserContext != nil {
		const prefix string = ",\"userContext\":"
		first = false
		out.RawString(prefix[1:])
		(*in.UserContext).MarshalEasyJSON(out)
	}
	if in.Id != "" {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Id))
	}
	if in.SagaId != nil {
		const prefix string = ",\"SagaId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SagaId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CompleteTaskCommand) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CompleteTaskCommand) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b8cbe4EncodePrototodoPkgDomainContracts13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CompleteTaskCommand) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CompleteTaskCommand) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b8cbe4DecodePrototodoPkgDomainContracts13(l, v)
}
