// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func initializeAppCQRS() (*appCQRS, error) {
	serverAppCQRS := newAppCQRS()
	return serverAppCQRS, nil
}

func initializeAppInMem() (*appInMem, error) {
	serverAppInMem := newAppInMem()
	return serverAppInMem, nil
}
