{
 "title": "Core Service Metrics - Prototodo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Web server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(promex_processed_reqs_total[1m]) * 60"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "promex_processed_reqs_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Request rate per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promex_processed_reqs_total[1m]) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(promex_processed_reqs_size_sum[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (promex_processed_reqs_status)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (promex_processed_reqs_status)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(promex_processed_reqs_latency_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(promex_processed_reqs_latency_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (promex_processed_reqs_latency_sum) / sum(promex_processed_reqs_latency_bucket)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GRPC HTTP",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ingress) (promex_processed_reqs_status)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(promex_processed_reqs_latency_sum{ingress=\"grpc\"}) / sum(promex_processed_reqs_latency_bucket{ingress=\"grpc\"})",
     "legendFormat": "grpc"
    },
    {
     "expr": "sum(promex_processed_reqs_latency_sum{ingress=\"http\"}) / sum(promex_processed_reqs_latency_bucket{ingress=\"http\"})",
     "legendFormat": "http"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_goroutines)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_threads)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 30 },
   "targets": [
    { "expr": "sum(go_goroutines)", "legendFormat": "__auto" },
    { "expr": "sum(go_threads)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_memstats_alloc_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IDK",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
   "options": { "content": "# Title\n\nWhy?" },
   "targets": [
    { "expr": "go_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "{{service}}-{{instance}}" }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes",
     "legendFormat": "go_memstats_mspan_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes",
     "legendFormat": "go_memstats_mspan_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes",
     "legendFormat": "go_memstats_mcache_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes",
     "legendFormat": "go_memstats_mcache_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes",
     "legendFormat": "go_memstats_buck_hash_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes",
     "legendFormat": "go_memstats_gc_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes - go_memstats_other_sys_bytes",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes",
     "legendFormat": "go_memstats_next_gc_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes",
     "legendFormat": "go_memstats_heap_alloc_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes",
     "legendFormat": "go_memstats_heap_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes",
     "legendFormat": "go_memstats_heap_idle_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes",
     "legendFormat": "go_memstats_heap_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "go_memstats_heap_released_bytes-{{service}}-{{instance}}"
    }
   ]
  }
 ]
}